# Generated by Django 3.2 on 2021-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webs',
            old_name='nick_name',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='webs',
            name='image',
            field=models.ImageField(default='', upload_to='screen/%Y-%m-%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webs',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webs',
            name='ship',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webs',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webs',
            name='url',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
