# Generated by Django 3.2 on 2021-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couweb', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created',), 'verbose_name': '카테고리들', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=10000000, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=10000000),
        ),
    ]
